<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ServicesMercury\\Mercury' => array($vendorDir . '/servicesmercury/mercury/src'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
);
